<?php

namespace AppBundle\Repository;

/**
 * notifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class notifRepository extends \Doctrine\ORM\EntityRepository
{
    public function afficherparusernotif($userid){//actualitedautreetab
        $query=$this->getEntityManager()
            ->createQuery(" SELECT n FROM AppBundle:notif n WHERE IDENTITY(n.user)!= :user_id AND n.date < CURRENT_TIMESTAMP() ORDER BY n.date DESC")
            ->setParameter('user_id',$userid)
        ->setMaxResults(3);
        return $query->getResult();
    }
}
