
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /front

back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /back

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix:   /message



